version: '3'

services:
  fashion-cloud:
    build: .
    image: fashion-cloud
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/fashion-cloud
      - fash_node_modules:/usr/src/fashion-cloud/node_modules
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  fash_node_modules:
